name: CI Smoke Test

on: [push, pull_request]  # run on every push or PR

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run smoke tests
      run: |
        # run your quick tests here
        pytest tests/smoke/  # or python scripts/smoke_test.py
